package vc;


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Apr 24 20:44:48 ICT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 39;
  public static final int GTEQ = 32;
  public static final int MULT = 37;
  public static final int LTEQ = 31;
  public static final int LPAREN = 17;
  public static final int CONTINUE = 7;
  public static final int INT = 11;
  public static final int MINUS = 36;
  public static final int FOR = 10;
  public static final int RPAREN = 18;
  public static final int OROR = 34;
  public static final int BOOLEAN_LITERAL = 16;
  public static final int NOT = 28;
  public static final int SEMICOLON = 23;
  public static final int LT = 27;
  public static final int DIV = 38;
  public static final int ANDAND = 33;
  public static final int PLUS = 35;
  public static final int IF = 12;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int RETURN = 13;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int EQEQ = 30;
  public static final int BREAK = 6;
  public static final int VOID = 14;
  public static final int EQ = 25;
  public static final int LBRACK = 21;
  public static final int FLOATING_POINT_LITERAL = 3;
  public static final int LBRACE = 19;
  public static final int ELSE = 8;
  public static final int RBRACK = 22;
  public static final int WHILE = 15;
  public static final int FLOAT = 9;
  public static final int RBRACE = 20;
  public static final int GT = 26;
  public static final int NOTEQ = 29;
  public static final int INTEGER_LITERAL = 4;
  public static final int IDENTIFIER = 2;  
}

